apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataprotection-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
