apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataprotection
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: c:/var/blazorserver1/dataprotection
    type: DirectoryOrCreate
