# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  nodename:
    image: localhost:5000/nodename
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
